"""
AI HR Recruitment Assistant — Streamlit App (OpenRouter-powered)
-------------------------------------------------------------------
Upload a resume, provide a job description, and get an AI-powered match
score, skill-gap analysis, personalized interview questions, a recruitment
recommendation, and a downloadable PDF report — all backed by a free
OpenRouter model (no local LLM / GPU required).

Run with:  streamlit run app.py
"""

import pandas as pd
import streamlit as st

from src.config import OPENROUTER_API_KEY, OPENROUTER_MODEL, ConfigError
from src.resume_parser import parse_resume, ResumeParsingError
from src.jd_parser import parse_job_description, extract_jd_text_from_file, JDParsingError
from src.matcher import compute_match, generate_match_explanation, generate_recommendation
from src.skill_extractor import build_skill_comparison_table
from src.interview_generator import generate_interview_questions
from src.rag import build_knowledge_base, KnowledgeBaseError
from src.report_generator import build_report_pdf
from src.agent import ask_agent, AgentError
from src.llm import LLMError


st.set_page_config(page_title="AI HR Recruitment Assistant", page_icon="🧑‍💼", layout="wide")

DISCLAIMER = (
    "AI-assisted recruitment support tool. Match scores, skill analysis, and "
    "recommendations are generated by AI and are **not** a final hiring decision. "
    "A human recruiter should always review this output before any hiring action."
)


# =====================================================================
# Theme / styling
# =====================================================================
def inject_css():
    st.markdown(
        """
        <style>
        @import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;500&display=swap');

        :root{
            --ink:#181c2a;
            --muted:#6b7280;
            --line:#e7e9f2;
            --card:#ffffff;
            --bg:#f6f7fb;
            --brand:#5b4cf5;
            --brand-2:#8a7bff;
            --good:#17a672;
            --good-bg:#e9faf3;
            --warn:#c98a09;
            --warn-bg:#fff6e0;
            --bad:#e0426b;
            --bad-bg:#fdecf1;
        }

        html, body, [class*="css"]  { font-family: 'Plus Jakarta Sans', sans-serif; }
        .stApp { background: var(--bg); }

        #MainMenu {visibility: hidden;}
        footer {visibility: hidden;}

        section[data-testid="stSidebar"] {
            background: #14162a;
            border-right: none;
        }
        section[data-testid="stSidebar"] * { color: #e6e6f5 !important; }
        section[data-testid="stSidebar"] .stCaption, section[data-testid="stSidebar"] small { color: #9a9cc0 !important; }
        section[data-testid="stSidebar"] hr { border-color: #2a2d4a; }

        .block-container { padding-top: 2rem; padding-bottom: 3rem; max-width: 1200px; }

        /* Hero */
        .hero {
            background: linear-gradient(120deg, var(--brand) 0%, var(--brand-2) 100%);
            border-radius: 22px;
            padding: 2.6rem 2.8rem;
            color: white;
            margin-bottom: 1.8rem;
            box-shadow: 0 16px 40px -20px rgba(91,76,245,0.55);
        }
        .hero h1 { margin: 0 0 .4rem 0; font-size: 2.1rem; font-weight: 800; letter-spacing: -0.02em; }
        .hero p { margin: 0; opacity: .92; font-size: 1.02rem; max-width: 640px; }
        .hero .steps { display:flex; gap: 1.6rem; margin-top: 1.6rem; flex-wrap: wrap; }
        .hero .step { background: rgba(255,255,255,0.14); border-radius: 12px; padding: .6rem 1rem; font-size: .88rem; font-weight: 600; }

        /* Generic card */
        .card {
            background: var(--card);
            border: 1px solid var(--line);
            border-radius: 18px;
            padding: 1.5rem 1.6rem;
            box-shadow: 0 1px 2px rgba(20,20,50,0.03);
        }
        .card h3, .card h4 { margin-top: 0; }
        .card-title {
            font-size: .78rem; font-weight: 700; text-transform: uppercase;
            letter-spacing: .06em; color: var(--muted); margin-bottom: .6rem;
        }

        /* Score cards */
        .score-row { display:flex; gap: 1rem; margin-bottom: 1.6rem; }
        .score-card {
            flex: 1; background: var(--card); border: 1px solid var(--line);
            border-radius: 18px; padding: 1.3rem 1.5rem; text-align:left;
            box-shadow: 0 1px 2px rgba(20,20,50,0.03);
        }
        .score-card .label { font-size:.78rem; font-weight:700; text-transform:uppercase; letter-spacing:.06em; color:var(--muted); }
        .score-card .value { font-size: 2.4rem; font-weight: 800; letter-spacing:-0.03em; margin-top:.15rem; }
        .score-bar-track { height:8px; border-radius:6px; background:#eef0f8; margin-top:.7rem; overflow:hidden; }
        .score-bar-fill { height:100%; border-radius:6px; }

        /* Pills */
        .pill-group { display:flex; flex-wrap:wrap; gap:.45rem; margin-top:.3rem; }
        .pill {
            display:inline-block; padding: .3rem .75rem; border-radius:999px;
            font-size:.82rem; font-weight:600; white-space:nowrap;
        }
        .pill-good { background: var(--good-bg); color: var(--good); }
        .pill-warn { background: var(--warn-bg); color: var(--warn); }
        .pill-bad  { background: var(--bad-bg); color: var(--bad); }
        .pill-neutral { background:#eef0f8; color:#3f4360; }

        /* Section headers inside tabs */
        .section-label {
            font-size:.78rem; font-weight:700; text-transform:uppercase; letter-spacing:.07em;
            color: var(--muted); margin: 1.4rem 0 .5rem 0;
        }

        /* Question card */
        .q-card {
            background: var(--card); border: 1px solid var(--line); border-left: 4px solid var(--brand);
            border-radius: 12px; padding: 1rem 1.2rem; margin-bottom: .8rem;
        }
        .q-card .q-tag { font-size:.72rem; font-weight:700; color: var(--brand); text-transform:uppercase; letter-spacing:.05em; }
        .q-card .q-text { font-weight:600; margin: .3rem 0 .5rem 0; color: var(--ink); }
        .q-card .q-meta { font-size:.85rem; color: var(--muted); }

        /* Recommendation banner */
        .rec-banner {
            border-radius: 18px; padding: 1.6rem 1.8rem; margin-bottom: 1rem;
            font-weight:700; font-size:1.2rem;
        }
        .rec-strong { background: var(--good-bg); color: var(--good); }
        .rec-consider { background: var(--warn-bg); color: var(--warn); }
        .rec-no { background: var(--bad-bg); color: var(--bad); }
        .rec-na { background:#eef0f8; color:#3f4360; }

        .disclaimer-bar {
            background: var(--warn-bg); color: #8a5c06; border-radius: 12px;
            padding: .7rem 1rem; font-size: .86rem; margin-bottom: 1.2rem;
            border: 1px solid #f3dfa8;
        }

        div[data-testid="stFileUploader"] section {
            border-radius: 14px; border: 1.5px dashed var(--line); background: #fbfbfe;
        }

        .stButton>button, .stDownloadButton>button {
            border-radius: 10px; font-weight: 700; padding: .55rem 1.3rem;
        }

        .stTabs [data-baseweb="tab-list"] { gap: .25rem; }
        .stTabs [data-baseweb="tab"] {
            border-radius: 10px 10px 0 0; padding: .6rem 1.1rem; font-weight: 600;
        }
        </style>
        """,
        unsafe_allow_html=True,
    )


def score_color(pct: float) -> str:
    if pct >= 75:
        return "#17a672"
    if pct >= 50:
        return "#c98a09"
    return "#e0426b"


def render_score_card(label: str, value: float) -> str:
    color = score_color(value)
    return f"""
    <div class="score-card">
        <div class="label">{label}</div>
        <div class="value" style="color:{color}">{value}%</div>
        <div class="score-bar-track">
            <div class="score-bar-fill" style="width:{min(100, max(0, value))}%; background:{color};"></div>
        </div>
    </div>
    """


def render_pills(items, kind="neutral") -> str:
    items = items or []
    if not items:
        return '<span class="pill pill-neutral">None</span>'
    cls = {"good": "pill-good", "warn": "pill-warn", "bad": "pill-bad"}.get(kind, "pill-neutral")
    return '<div class="pill-group">' + "".join(f'<span class="pill {cls}">{s}</span>' for s in items) + "</div>"


# =====================================================================
# Session state
# =====================================================================
for key in ["resume", "jd", "match_result", "explanation", "questions", "recommendation", "chat_history"]:
    if key not in st.session_state:
        st.session_state[key] = None
if st.session_state["chat_history"] is None:
    st.session_state["chat_history"] = []


def reset_analysis():
    for key in ["match_result", "explanation", "questions", "recommendation"]:
        st.session_state[key] = None


def reset_all():
    for key in ["resume", "jd", "match_result", "explanation", "questions", "recommendation"]:
        st.session_state[key] = None
    st.session_state["chat_history"] = []


def show_friendly_error(exc: Exception):
    st.error(f"⚠️ {exc}")


inject_css()

has_result = bool(st.session_state["resume"] and st.session_state["jd"] and st.session_state["match_result"])

# =====================================================================
# Sidebar — brand + status only
# =====================================================================
with st.sidebar:
    st.markdown("### 🧑‍💼 HR Recruitment Assistant")
    st.caption("Resume screening · JD matching · skill gaps · interview prep")
    st.divider()

    st.markdown("**API status**")
    if OPENROUTER_API_KEY:
        st.success("Configured ✅", icon="🔑")
    else:
        st.error("Missing API key ❌")
        st.caption("Copy `.env.example` to `.env` and add a free key from https://openrouter.ai/keys")
    st.caption(f"Model: `{OPENROUTER_MODEL}`")

    st.divider()
    if has_result:
        st.markdown(f"**Candidate:** {st.session_state['resume'].get('name', 'Unknown')}")
        st.markdown(f"**Role:** {st.session_state['jd'].get('job_title', '—')}")
        if st.button("↺ Start new analysis", use_container_width=True):
            reset_all()
            st.rerun()

    st.divider()
    st.caption(DISCLAIMER)


# =====================================================================
# Setup screen (no analysis yet) — main area, not the sidebar
# =====================================================================
if not has_result:
    st.markdown(
        """
        <div class="hero">
            <h1>Screen candidates in minutes, not hours</h1>
            <p>Upload a resume and a job description to get an AI match score, a skill-gap
            breakdown, tailored interview questions, and a recruiter-ready recommendation.</p>
            <div class="steps">
                <div class="step">① Upload resume</div>
                <div class="step">② Add job description</div>
                <div class="step">③ Get your analysis</div>
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    col1, col2 = st.columns(2, gap="large")
    with col1:
        st.markdown('<div class="card">', unsafe_allow_html=True)
        st.markdown('<div class="card-title">Step 1 · Candidate resume</div>', unsafe_allow_html=True)
        resume_file = st.file_uploader("PDF or DOCX resume", type=["pdf", "docx"], key="resume_uploader",
                                        label_visibility="collapsed")
        st.markdown("</div>", unsafe_allow_html=True)

    with col2:
        st.markdown('<div class="card">', unsafe_allow_html=True)
        st.markdown('<div class="card-title">Step 2 · Job description</div>', unsafe_allow_html=True)
        jd_input_mode = st.radio("Provide JD as:", ["Paste text", "Upload file"], horizontal=True,
                                  label_visibility="collapsed")
        jd_text_input, jd_file = "", None
        if jd_input_mode == "Paste text":
            jd_text_input = st.text_area("Paste the job description", height=160,
                                          placeholder="Paste the full job description here…",
                                          label_visibility="collapsed")
        else:
            jd_file = st.file_uploader("PDF or DOCX job description", type=["pdf", "docx"], key="jd_uploader",
                                        label_visibility="collapsed")
        st.markdown("</div>", unsafe_allow_html=True)

    st.write("")
    _, mid, _ = st.columns([1, 1, 1])
    with mid:
        analyze_clicked = st.button("🔍  Analyze Candidate", type="primary", use_container_width=True)

    st.markdown(f'<div class="disclaimer-bar">⚠️ {DISCLAIMER}</div>', unsafe_allow_html=True)

    # ---------- Analysis pipeline ----------
    if analyze_clicked:
        if not OPENROUTER_API_KEY:
            st.error("Please configure OPENROUTER_API_KEY in your .env file first.")
        elif not resume_file:
            st.warning("Please upload a resume.")
        elif jd_input_mode == "Paste text" and not jd_text_input.strip():
            st.warning("Please paste a job description.")
        elif jd_input_mode == "Upload file" and not jd_file:
            st.warning("Please upload a job description file.")
        else:
            reset_analysis()
            try:
                with st.spinner("Parsing resume..."):
                    resume_data = parse_resume(resume_file.read(), resume_file.name)
                    st.session_state["resume"] = resume_data

                with st.spinner("Parsing job description..."):
                    if jd_input_mode == "Upload file":
                        jd_raw_text = extract_jd_text_from_file(jd_file.read(), jd_file.name)
                    else:
                        jd_raw_text = jd_text_input
                    jd_data = parse_job_description(jd_raw_text)
                    st.session_state["jd"] = jd_data

                with st.spinner("Preparing recruitment knowledge base..."):
                    build_knowledge_base()

                with st.spinner("Computing match score and skill gaps..."):
                    match_result = compute_match(resume_data, jd_data)
                    st.session_state["match_result"] = match_result

                with st.spinner("Generating match explanation..."):
                    st.session_state["explanation"] = generate_match_explanation(resume_data, jd_data, match_result)

                with st.spinner("Generating interview questions..."):
                    st.session_state["questions"] = generate_interview_questions(resume_data, jd_data, match_result)

                with st.spinner("Generating recommendation..."):
                    st.session_state["recommendation"] = generate_recommendation(resume_data, jd_data, match_result)

                st.success("Analysis complete!")
                st.rerun()

            except (ResumeParsingError, JDParsingError, KnowledgeBaseError, ConfigError, LLMError) as exc:
                reset_analysis()
                show_friendly_error(exc)
            except Exception as exc:  # last-resort safety net, never show a raw traceback
                reset_analysis()
                show_friendly_error(f"Something unexpected went wrong: {exc}")

    st.stop()


# =====================================================================
# Results
# =====================================================================
resume = st.session_state["resume"]
jd = st.session_state["jd"]
match_result = st.session_state["match_result"]

st.markdown(
    f"""
    <div class="hero" style="padding:1.6rem 2rem;">
        <h1 style="font-size:1.5rem;">{resume.get('name', 'Unknown Candidate')}</h1>
        <p>Applying for <strong>{jd.get('job_title', '—')}</strong>
        {f"at {jd.get('company')}" if jd.get('company') else ""}</p>
    </div>
    """,
    unsafe_allow_html=True,
)

st.markdown(
    '<div class="score-row">'
    + render_score_card("Overall Match", match_result["match_score"])
    + render_score_card("Semantic Fit", match_result["semantic_similarity"])
    + render_score_card("Experience Fit", match_result["experience_fit_pct"])
    + "</div>",
    unsafe_allow_html=True,
)

tab_overview, tab_skills, tab_questions, tab_recommendation, tab_agent, tab_report = st.tabs(
    ["📋 Overview", "🧩 Skill Comparison", "❓ Interview Questions", "✅ Recommendation", "🤖 Ask the Agent", "📄 Report"]
)

with tab_overview:
    left, right = st.columns(2, gap="large")
    with left:
        st.markdown('<div class="card">', unsafe_allow_html=True)
        st.markdown('<div class="card-title">Resume summary</div>', unsafe_allow_html=True)
        st.write(resume.get("summary", "—"))
        st.markdown(f"**Total experience:** {resume.get('total_experience_years', 0)} years")
        st.markdown("**Skills**")
        st.markdown(render_pills(resume.get("skills", []), "neutral"), unsafe_allow_html=True)
        st.markdown("</div>", unsafe_allow_html=True)
        st.write("")

        with st.expander("🎓 Education"):
            for edu in resume.get("education", []) or []:
                st.write(f"- {edu.get('degree')} — {edu.get('institution')} ({edu.get('year')}) {edu.get('score')}")
        with st.expander("💼 Experience"):
            for exp in resume.get("experience", []) or []:
                st.write(f"- **{exp.get('title')}** at {exp.get('company')} ({exp.get('duration')}): {exp.get('description')}")
        with st.expander("🕒 Job History"):
            for job in resume.get("job_history", []) or []:
                st.write(f"- {job.get('title')} at {job.get('company')} ({job.get('start_date')} – {job.get('end_date')})")
        with st.expander("🚀 Projects"):
            for proj in resume.get("projects", []) or []:
                st.write(f"- **{proj.get('name')}**: {proj.get('description')} — _{', '.join(proj.get('technologies', []))}_")
        with st.expander("📜 Certifications"):
            for cert in resume.get("certifications", []) or []:
                st.write(f"- {cert}")

    with right:
        st.markdown('<div class="card">', unsafe_allow_html=True)
        st.markdown('<div class="card-title">Job description</div>', unsafe_allow_html=True)
        st.markdown(f"**Min. experience:** {jd.get('min_experience_years', 0)} years")
        st.markdown("**Required skills**")
        st.markdown(render_pills(jd.get("required_skills", []), "neutral"), unsafe_allow_html=True)
        st.markdown("**Preferred skills**")
        st.markdown(render_pills(jd.get("preferred_skills", []), "neutral"), unsafe_allow_html=True)
        st.markdown("</div>", unsafe_allow_html=True)
        st.write("")

        with st.expander("📋 Responsibilities"):
            for r in jd.get("responsibilities", []) or []:
                st.write(f"- {r}")
        with st.expander("🛠️ Technical Requirements"):
            for t in jd.get("technical_requirements", []) or []:
                st.write(f"- {t}")
        with st.expander("🤝 Soft Skills"):
            for s in jd.get("soft_skills", []) or []:
                st.write(f"- {s}")
        with st.expander("✔️ Qualifications"):
            for q in jd.get("qualifications", []) or []:
                st.write(f"- {q}")

    st.markdown('<div class="section-label">AI explanation</div>', unsafe_allow_html=True)
    st.markdown('<div class="card">', unsafe_allow_html=True)
    st.write(st.session_state["explanation"])
    st.markdown("</div>", unsafe_allow_html=True)

with tab_skills:
    st.markdown('<div class="card">', unsafe_allow_html=True)
    st.markdown('<div class="card-title">Skill comparison</div>', unsafe_allow_html=True)
    comparison_rows = build_skill_comparison_table(
        resume.get("skills", []) or [], jd.get("required_skills", []) or [], jd.get("preferred_skills", []) or []
    )
    st.dataframe(pd.DataFrame(comparison_rows), use_container_width=True, hide_index=True)
    st.markdown("</div>", unsafe_allow_html=True)

    st.markdown('<div class="section-label">Required skills — gap analysis</div>', unsafe_allow_html=True)
    req = match_result["required_skills"]
    c1, c2, c3 = st.columns(3)
    with c1:
        st.markdown('<div class="card"><div class="card-title" style="color:#17a672;">✓ Strong match</div>', unsafe_allow_html=True)
        st.markdown(render_pills(req["strong_match"], "good"), unsafe_allow_html=True)
        st.markdown("</div>", unsafe_allow_html=True)
    with c2:
        st.markdown('<div class="card"><div class="card-title" style="color:#c98a09;">~ Partial match</div>', unsafe_allow_html=True)
        st.markdown(render_pills(req["partial_match"], "warn"), unsafe_allow_html=True)
        st.markdown("</div>", unsafe_allow_html=True)
    with c3:
        st.markdown('<div class="card"><div class="card-title" style="color:#e0426b;">✗ Missing</div>', unsafe_allow_html=True)
        st.markdown(render_pills(req["missing"], "bad"), unsafe_allow_html=True)
        st.markdown("</div>", unsafe_allow_html=True)

    st.markdown('<div class="section-label">Preferred skills — gap analysis</div>', unsafe_allow_html=True)
    pref = match_result["preferred_skills"]
    c4, c5, c6 = st.columns(3)
    with c4:
        st.markdown('<div class="card"><div class="card-title" style="color:#17a672;">✓ Strong match</div>', unsafe_allow_html=True)
        st.markdown(render_pills(pref["strong_match"], "good"), unsafe_allow_html=True)
        st.markdown("</div>", unsafe_allow_html=True)
    with c5:
        st.markdown('<div class="card"><div class="card-title" style="color:#c98a09;">~ Partial match</div>', unsafe_allow_html=True)
        st.markdown(render_pills(pref["partial_match"], "warn"), unsafe_allow_html=True)
        st.markdown("</div>", unsafe_allow_html=True)
    with c6:
        st.markdown('<div class="card"><div class="card-title" style="color:#e0426b;">✗ Missing</div>', unsafe_allow_html=True)
        st.markdown(render_pills(pref["missing"], "bad"), unsafe_allow_html=True)
        st.markdown("</div>", unsafe_allow_html=True)

with tab_questions:
    questions = st.session_state["questions"] or {}
    for section_title, key in [
        ("Technical Questions", "technical_questions"),
        ("Behavioral Questions", "behavioral_questions"),
        ("Role-Specific Questions", "role_specific_questions"),
        ("Skill-Gap Questions", "skill_gap_questions"),
    ]:
        st.markdown(f'<div class="section-label">{section_title}</div>', unsafe_allow_html=True)
        for q in questions.get(key, []) or []:
            eval_points = "".join(f"<li>{p}</li>" for p in (q.get("evaluation_points", []) or []))
            strong_answer = (
                f"<div class='q-meta' style='margin-top:.4rem;'><strong>Expected strong answer:</strong> {q.get('expected_strong_answer')}</div>"
                if q.get("expected_strong_answer") else ""
            )
            st.markdown(
                f"""
                <div class="q-card">
                    <div class="q-tag">{q.get('category', section_title)}</div>
                    <div class="q-text">{q.get('question')}</div>
                    <div class="q-meta">Why this question: {q.get('why_relevant', '—')}</div>
                    <div class="q-meta" style="margin-top:.4rem;"><strong>Evaluation points:</strong>
                        <ul style="margin:.2rem 0 0 1.1rem;">{eval_points}</ul>
                    </div>
                    {strong_answer}
                </div>
                """,
                unsafe_allow_html=True,
            )

with tab_recommendation:
    rec = st.session_state["recommendation"] or {}
    decision = rec.get("decision", "N/A")
    banner_class = {
        "Strongly Recommend": "rec-strong", "Recommend": "rec-strong",
        "Consider": "rec-consider", "Not Recommended": "rec-no",
    }.get(decision, "rec-na")
    st.markdown(f'<div class="rec-banner {banner_class}">Recommendation: {decision}</div>', unsafe_allow_html=True)
    st.markdown('<div class="card">', unsafe_allow_html=True)
    st.write(rec.get("explanation", ""))
    st.markdown("</div>", unsafe_allow_html=True)
    st.caption(f"⚠️ {DISCLAIMER}")

with tab_agent:
    st.markdown('<div class="card-title">Ask the AI recruitment agent</div>', unsafe_allow_html=True)
    st.caption("Ask follow-up questions — the agent decides whether to recompute the match, "
               "search recruitment knowledge, regenerate interview questions, or produce a "
               "fresh recommendation.")

    for role, msg in st.session_state["chat_history"]:
        with st.chat_message(role):
            st.write(msg)

    user_q = st.chat_input("e.g. 'Focus interview questions on their Docker gap'")
    if user_q:
        st.session_state["chat_history"].append(("user", user_q))
        try:
            with st.spinner("Agent is reasoning..."):
                answer = ask_agent(user_q, resume, jd)
            st.session_state["chat_history"].append(("assistant", answer))
        except (AgentError, LLMError) as exc:
            st.session_state["chat_history"].append(("assistant", f"⚠️ {exc}"))
        st.rerun()

with tab_report:
    st.markdown('<div class="card">', unsafe_allow_html=True)
    st.markdown('<div class="card-title">Downloadable recruitment report</div>', unsafe_allow_html=True)
    st.caption(f"⚠️ {DISCLAIMER}")
    if st.button("📄 Generate PDF Report"):
        try:
            with st.spinner("Building report..."):
                pdf_bytes = build_report_pdf(
                    resume, jd, match_result,
                    st.session_state["explanation"],
                    st.session_state["questions"],
                    st.session_state["recommendation"],
                )
            st.download_button(
                "⬇️ Download Report",
                data=pdf_bytes,
                file_name=f"{resume.get('name', 'candidate').replace(' ', '_')}_recruitment_report.pdf",
                mime="application/pdf",
            )
        except Exception as exc:
            show_friendly_error(f"Could not generate the report: {exc}")
    st.markdown("</div>", unsafe_allow_html=True)
